export const targetLanguageLabels: Record<string, { phonetic: string; meaning: string; }> = {
    French: { phonetic: "Phonétique", meaning: "Signification" },
    German: { phonetic: "Phonetisch", meaning: "Bedeutung" },
    Spanish: { phonetic: "Fonética", meaning: "Significado" },
    Italian: { phonetic: "Fonetico", meaning: "Significato" },
    Portuguese: { phonetic: "Fonética", meaning: "Significado" },
    Dutch: { phonetic: "Fonetisch", meaning: "Betekenis" },
    Polish: { phonetic: "Fonetyka", meaning: "Znaczenie" },
    Romanian: { phonetic: "Fonetică", meaning: "Înțeles" },
    Greek: { phonetic: "Φωνητική", meaning: "Σημασία" },
    Serbian: { phonetic: "Фонетика", meaning: "Значење" },
    Russian: { phonetic: "Фонетика", meaning: "Значение" },
    Finnish: { phonetic: "Foneettinen", meaning: "Merkitys" },
    Korean: { phonetic: "발음", meaning: "의미" },
    Japanese: { phonetic: "発音", meaning: "意味" },
    Arabic: { phonetic: "صوتي", meaning: "المعنى" },
    Hebrew: { phonetic: "פונטיקה", meaning: "משמעות" },
    English: { phonetic: "Phonetic", meaning: "Meaning" },
};
