'use client';

// === Main Lesson Structure ===

// This interface represents the exact structure of a daily lesson JSON file.
export interface LessonDay {
  week: number;
  day: number;
  letter?: string; // The character for the alphabet path
  title: string;
  title_native: string;
  theme: string;
  path: "survival" | "alphabet" | "numbers";
  targetLanguage: string;
  nativeLanguage: string;
  words?: LessonItem[];
  sentences?: SentenceItem[];
  dialogues?: Dialogue[];
  exercises: Exercises;
  cultural_note?: string;
  pronunciation_tip?: string;
  progress: {
    xp: number;
    streak_bonus: number;
    badge: string;
  };
}

// Represents a standalone sentence for practice.
export interface SentenceItem {
    id: string;
    target: string;
    native: string;
    phonetic: string;
}

// A wrapper structure for consistency, holding the daily lesson data for the client page.
export interface LanguageLesson {
  week: number;
  language: string;
  path: "survival" | "alphabet" | "numbers";
  title: string;
  description: string;
  days: LessonDay[]; // Will only contain ONE day's data for the client page.
}

// Represents the full 7-day lesson plan generated by the AI and stored in the cache.
export interface WeeklyLessonPlan {
  week: number;
  path: string;
  targetLanguage: string;
  nativeLanguage: string;
  days: LessonDay[]; // Contains all 7 days for the week.
}

export interface LessonItem {
  id: string;
  target: string;
  phonetic: string;
  native_meaning: string;
  english: string;
  example_sentence_target: string;
  example_sentence_native: string;
  example_sentence_phonetic: string;
}

export interface DialogueLine {
  speaker: "A" | "B";
  target: string;
  native: string;
  phonetic: string;
}

export interface Dialogue {
  id:string;
  context: string;
  lines: DialogueLine[];
}

export interface FillBlankExercise {
  id: string;
  sentence: string;
  answer: string;
  hint: string;
}

export interface MultipleChoiceExercise {
  id: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export interface MatchingPair {
  id: string;
  target: string;
  native: string;
}

export interface SentenceScrambleExercise {
  id: string;
  scrambled: string[];
  correct: string;
  nativeHint: string;
}

export interface WritingPracticeExercise {
  id: string;
  letter: string;
  hint?: string;
}

export interface Exercises {
  fillBlanks?: FillBlankExercise[];
  multipleChoice?: MultipleChoiceExercise[];
  matching?: MatchingPair[];
  sentenceScramble?: SentenceScrambleExercise[];
  writingPractice?: WritingPracticeExercise[];
}


// === Firestore Data Structures ===

export interface LessonCache {
  id: string;
  lessonJson: string;
  cachedAt: any; // Firestore Timestamp
}

export interface UserProfile {
  id: string;
  displayName: string;
  email: string;
  nativeLanguage: string;
  selectedLanguage: string;
  createdAt: string; // ISO date string
  subscriptionActive: boolean;
  subscriptionSource?: 'stripe' | 'google_play' | 'apple_iap' | 'lemonsqueezy' | 'none';
  subscriptionPlan?: 'weekly' | 'course' | 'lifetime';
  subscriptionLanguage?: string;
  subscriptionExpiry: string | null; // ISO date string, or null for lifetime
  xpPoints: number;
  currentStreak: number;
  lastActiveDate: string; // ISO 8601 date string
  aiPlanningEnabled: boolean;
  photoURL?: string;
  activePath: 'survival' | 'alphabet' | 'numbers';
  lastLessonWeek: number;
  lastLessonDay: number;
  completedDays?: string[];
  paymentProviderCustomerId?: string;
  paymentProviderSubscriptionId?: string;
  referralCode?: string;
  referredBy?: string;
  bonusWeeks?: number;
  referralCount?: number;
}

export interface UserLessonProgress {
  completed: boolean;
  score: number;
  completedAt: any;
  exerciseResults: {
    [exerciseId: string]: boolean;
  };
}

export interface UserWeekProgress {
  week: number;
  path: string;
  daysCompleted: number[];
  weekCompleted: boolean;
  selectedTopic?: string;
}


// === App-specific types ===

export type LearningPath = "survival" | "alphabet" | "numbers";

export type TargetLanguage =
  | "French" | "German" | "Spanish" | "Italian" | "Portuguese"
  | "Dutch" | "Polish" | "Romanian" | "Greek" | "Serbian"
  | "Russian" | "Finnish" | "Korean" | "Japanese" | "Arabic"
  | "Hebrew" | "English" | "Turkish" | "Hindi" | "Tamil" | "Chinese";

export type NativeLanguage = "English" | "Sinhala" | "Hindi" | "Urdu" | "Arabic" | "Bengali" | "Nepali";

export interface Language {
  code: string;
  name: TargetLanguage;
  flag: string;
}
