'use client';

import { Navigation } from "@/components/Navigation";

export default function TermsPage() {
  return (
    <div className="flex min-h-dvh flex-col bg-background">
      <Navigation />
      <main className="flex-1">
        <div className="container mx-auto max-w-3xl py-12 px-4">
          <div className="prose prose-invert mx-auto">
            <h1>Terms and Conditions for LingoForge</h1>
            <p><em>Last Updated: May 17, 2026</em></p>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing and using LingoForge ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the Service.</p>

            <h2>2. Description of Service</h2>
            <p>LingoForge is an AI-powered language learning platform designed for migrant workers and international professionals. The Service includes survival language lessons, alphabet and numbers paths, and AI-generated citizenship and integration lessons (LingoForge Pro).</p>

            <h2>3. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to accept responsibility for all activities that occur under your account.</p>

            <h2>4. Free Access and Paid Plans</h2>
            <p>LingoForge offers free access to the first 3 days of every learning path. Full access requires a one-time payment:</p>
            <ul>
              <li><strong>Survival Bundle</strong> — $26 one-time payment. Unlocks full survival path for one language.</li>
              <li><strong>Lifetime Pro</strong> — $49 one-time payment. Unlocks all languages, all paths, and LingoForge Pro AI lessons forever.</li>
            </ul>
            <p>All payments are one-time only. There are no recurring subscriptions or hidden fees.</p>

            <h2>5. Refund Policy</h2>
            <p>We offer a 7-day money-back guarantee. If you are not satisfied with your purchase, contact us at <strong>support@lingoforge.app</strong> within 7 days of payment for a full refund.</p>

            <h2>6. AI-Generated Content</h2>
            <p>LingoForge Pro lessons are generated by AI (powered by Anthropic Claude). While we strive for accuracy, AI-generated content may contain errors. Do not rely solely on AI-generated content for legal, medical, or official purposes.</p>

            <h2>7. Intellectual Property</h2>
            <p>All content, design, and code of LingoForge is the property of LingoForge and its creator. You may not reproduce, distribute, or create derivative works without explicit permission.</p>

            <h2>8. Prohibited Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Share your account credentials with others</li>
              <li>Reverse engineer or copy any part of the Service</li>
            </ul>

            <h2>9. Privacy</h2>
            <p>Your use of the Service is also governed by our Privacy Policy. We collect only the data necessary to provide the Service and do not sell your personal data to third parties.</p>

            <h2>10. Disclaimer of Warranties</h2>
            <p>The Service is provided "as is" without warranties of any kind. LingoForge does not guarantee that the Service will be uninterrupted or error-free.</p>

            <h2>11. Limitation of Liability</h2>
            <p>LingoForge shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>

            <h2>12. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>

            <h2>13. Contact</h2>
            <p>For any questions regarding these Terms, please contact us at: <strong>support@lingoforge.app</strong></p>
          </div>
        </div>
      </main>
    </div>
  );
}
